// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.1
 * source: realionetwork/multistaking/v1/multi_staking.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_3 from "./../../../cosmos/staking/v1beta1/staking";
import * as dependency_4 from "./../../../google/protobuf/timestamp";
import * as dependency_5 from "./../../../google/protobuf/any";
import * as pb_1 from "google-protobuf";
export namespace multistaking.v1 {
    export class MultiStakingCoin extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            denom?: string;
            amount?: string;
            bond_weight?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("denom" in data && data.denom != undefined) {
                    this.denom = data.denom;
                }
                if ("amount" in data && data.amount != undefined) {
                    this.amount = data.amount;
                }
                if ("bond_weight" in data && data.bond_weight != undefined) {
                    this.bond_weight = data.bond_weight;
                }
            }
        }
        get denom() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set denom(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get amount() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set amount(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get bond_weight() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set bond_weight(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            denom?: string;
            amount?: string;
            bond_weight?: string;
        }): MultiStakingCoin {
            const message = new MultiStakingCoin({});
            if (data.denom != null) {
                message.denom = data.denom;
            }
            if (data.amount != null) {
                message.amount = data.amount;
            }
            if (data.bond_weight != null) {
                message.bond_weight = data.bond_weight;
            }
            return message;
        }
        toObject() {
            const data: {
                denom?: string;
                amount?: string;
                bond_weight?: string;
            } = {};
            if (this.denom != null) {
                data.denom = this.denom;
            }
            if (this.amount != null) {
                data.amount = this.amount;
            }
            if (this.bond_weight != null) {
                data.bond_weight = this.bond_weight;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.denom.length)
                writer.writeString(1, this.denom);
            if (this.amount.length)
                writer.writeString(2, this.amount);
            if (this.bond_weight.length)
                writer.writeString(3, this.bond_weight);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MultiStakingCoin {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MultiStakingCoin();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.denom = reader.readString();
                        break;
                    case 2:
                        message.amount = reader.readString();
                        break;
                    case 3:
                        message.bond_weight = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MultiStakingCoin {
            return MultiStakingCoin.deserialize(bytes);
        }
    }
    export class LockID extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            multi_staker_addr?: string;
            val_addr?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("multi_staker_addr" in data && data.multi_staker_addr != undefined) {
                    this.multi_staker_addr = data.multi_staker_addr;
                }
                if ("val_addr" in data && data.val_addr != undefined) {
                    this.val_addr = data.val_addr;
                }
            }
        }
        get multi_staker_addr() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set multi_staker_addr(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get val_addr() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set val_addr(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            multi_staker_addr?: string;
            val_addr?: string;
        }): LockID {
            const message = new LockID({});
            if (data.multi_staker_addr != null) {
                message.multi_staker_addr = data.multi_staker_addr;
            }
            if (data.val_addr != null) {
                message.val_addr = data.val_addr;
            }
            return message;
        }
        toObject() {
            const data: {
                multi_staker_addr?: string;
                val_addr?: string;
            } = {};
            if (this.multi_staker_addr != null) {
                data.multi_staker_addr = this.multi_staker_addr;
            }
            if (this.val_addr != null) {
                data.val_addr = this.val_addr;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.multi_staker_addr.length)
                writer.writeString(1, this.multi_staker_addr);
            if (this.val_addr.length)
                writer.writeString(2, this.val_addr);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LockID {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new LockID();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.multi_staker_addr = reader.readString();
                        break;
                    case 2:
                        message.val_addr = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): LockID {
            return LockID.deserialize(bytes);
        }
    }
    export class MultiStakingLock extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            lockID?: LockID;
            locked_coin?: MultiStakingCoin;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("lockID" in data && data.lockID != undefined) {
                    this.lockID = data.lockID;
                }
                if ("locked_coin" in data && data.locked_coin != undefined) {
                    this.locked_coin = data.locked_coin;
                }
            }
        }
        get lockID() {
            return pb_1.Message.getWrapperField(this, LockID, 1) as LockID;
        }
        set lockID(value: LockID) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_lockID() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get locked_coin() {
            return pb_1.Message.getWrapperField(this, MultiStakingCoin, 2) as MultiStakingCoin;
        }
        set locked_coin(value: MultiStakingCoin) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_locked_coin() {
            return pb_1.Message.getField(this, 2) != null;
        }
        static fromObject(data: {
            lockID?: ReturnType<typeof LockID.prototype.toObject>;
            locked_coin?: ReturnType<typeof MultiStakingCoin.prototype.toObject>;
        }): MultiStakingLock {
            const message = new MultiStakingLock({});
            if (data.lockID != null) {
                message.lockID = LockID.fromObject(data.lockID);
            }
            if (data.locked_coin != null) {
                message.locked_coin = MultiStakingCoin.fromObject(data.locked_coin);
            }
            return message;
        }
        toObject() {
            const data: {
                lockID?: ReturnType<typeof LockID.prototype.toObject>;
                locked_coin?: ReturnType<typeof MultiStakingCoin.prototype.toObject>;
            } = {};
            if (this.lockID != null) {
                data.lockID = this.lockID.toObject();
            }
            if (this.locked_coin != null) {
                data.locked_coin = this.locked_coin.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_lockID)
                writer.writeMessage(1, this.lockID, () => this.lockID.serialize(writer));
            if (this.has_locked_coin)
                writer.writeMessage(2, this.locked_coin, () => this.locked_coin.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MultiStakingLock {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MultiStakingLock();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.lockID, () => message.lockID = LockID.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.locked_coin, () => message.locked_coin = MultiStakingCoin.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MultiStakingLock {
            return MultiStakingLock.deserialize(bytes);
        }
    }
    export class ValidatorMultiStakingCoin extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            val_addr?: string;
            coin_denom?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("val_addr" in data && data.val_addr != undefined) {
                    this.val_addr = data.val_addr;
                }
                if ("coin_denom" in data && data.coin_denom != undefined) {
                    this.coin_denom = data.coin_denom;
                }
            }
        }
        get val_addr() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set val_addr(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get coin_denom() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set coin_denom(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            val_addr?: string;
            coin_denom?: string;
        }): ValidatorMultiStakingCoin {
            const message = new ValidatorMultiStakingCoin({});
            if (data.val_addr != null) {
                message.val_addr = data.val_addr;
            }
            if (data.coin_denom != null) {
                message.coin_denom = data.coin_denom;
            }
            return message;
        }
        toObject() {
            const data: {
                val_addr?: string;
                coin_denom?: string;
            } = {};
            if (this.val_addr != null) {
                data.val_addr = this.val_addr;
            }
            if (this.coin_denom != null) {
                data.coin_denom = this.coin_denom;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.val_addr.length)
                writer.writeString(1, this.val_addr);
            if (this.coin_denom.length)
                writer.writeString(2, this.coin_denom);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ValidatorMultiStakingCoin {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ValidatorMultiStakingCoin();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.val_addr = reader.readString();
                        break;
                    case 2:
                        message.coin_denom = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ValidatorMultiStakingCoin {
            return ValidatorMultiStakingCoin.deserialize(bytes);
        }
    }
    export class UnlockID extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            multi_staker_addr?: string;
            val_addr?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("multi_staker_addr" in data && data.multi_staker_addr != undefined) {
                    this.multi_staker_addr = data.multi_staker_addr;
                }
                if ("val_addr" in data && data.val_addr != undefined) {
                    this.val_addr = data.val_addr;
                }
            }
        }
        get multi_staker_addr() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set multi_staker_addr(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get val_addr() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set val_addr(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            multi_staker_addr?: string;
            val_addr?: string;
        }): UnlockID {
            const message = new UnlockID({});
            if (data.multi_staker_addr != null) {
                message.multi_staker_addr = data.multi_staker_addr;
            }
            if (data.val_addr != null) {
                message.val_addr = data.val_addr;
            }
            return message;
        }
        toObject() {
            const data: {
                multi_staker_addr?: string;
                val_addr?: string;
            } = {};
            if (this.multi_staker_addr != null) {
                data.multi_staker_addr = this.multi_staker_addr;
            }
            if (this.val_addr != null) {
                data.val_addr = this.val_addr;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.multi_staker_addr.length)
                writer.writeString(1, this.multi_staker_addr);
            if (this.val_addr.length)
                writer.writeString(2, this.val_addr);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UnlockID {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UnlockID();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.multi_staker_addr = reader.readString();
                        break;
                    case 2:
                        message.val_addr = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UnlockID {
            return UnlockID.deserialize(bytes);
        }
    }
    export class MultiStakingUnlock extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            unlockID?: UnlockID;
            entries?: UnlockEntry[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("unlockID" in data && data.unlockID != undefined) {
                    this.unlockID = data.unlockID;
                }
                if ("entries" in data && data.entries != undefined) {
                    this.entries = data.entries;
                }
            }
        }
        get unlockID() {
            return pb_1.Message.getWrapperField(this, UnlockID, 1) as UnlockID;
        }
        set unlockID(value: UnlockID) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_unlockID() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get entries() {
            return pb_1.Message.getRepeatedWrapperField(this, UnlockEntry, 2) as UnlockEntry[];
        }
        set entries(value: UnlockEntry[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            unlockID?: ReturnType<typeof UnlockID.prototype.toObject>;
            entries?: ReturnType<typeof UnlockEntry.prototype.toObject>[];
        }): MultiStakingUnlock {
            const message = new MultiStakingUnlock({});
            if (data.unlockID != null) {
                message.unlockID = UnlockID.fromObject(data.unlockID);
            }
            if (data.entries != null) {
                message.entries = data.entries.map(item => UnlockEntry.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                unlockID?: ReturnType<typeof UnlockID.prototype.toObject>;
                entries?: ReturnType<typeof UnlockEntry.prototype.toObject>[];
            } = {};
            if (this.unlockID != null) {
                data.unlockID = this.unlockID.toObject();
            }
            if (this.entries != null) {
                data.entries = this.entries.map((item: UnlockEntry) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_unlockID)
                writer.writeMessage(1, this.unlockID, () => this.unlockID.serialize(writer));
            if (this.entries.length)
                writer.writeRepeatedMessage(2, this.entries, (item: UnlockEntry) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MultiStakingUnlock {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MultiStakingUnlock();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.unlockID, () => message.unlockID = UnlockID.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.entries, () => pb_1.Message.addToRepeatedWrapperField(message, 2, UnlockEntry.deserialize(reader), UnlockEntry));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MultiStakingUnlock {
            return MultiStakingUnlock.deserialize(bytes);
        }
    }
    export class UnlockEntry extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            creation_height?: number;
            unlocking_coin?: MultiStakingCoin;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("creation_height" in data && data.creation_height != undefined) {
                    this.creation_height = data.creation_height;
                }
                if ("unlocking_coin" in data && data.unlocking_coin != undefined) {
                    this.unlocking_coin = data.unlocking_coin;
                }
            }
        }
        get creation_height() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set creation_height(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get unlocking_coin() {
            return pb_1.Message.getWrapperField(this, MultiStakingCoin, 2) as MultiStakingCoin;
        }
        set unlocking_coin(value: MultiStakingCoin) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_unlocking_coin() {
            return pb_1.Message.getField(this, 2) != null;
        }
        static fromObject(data: {
            creation_height?: number;
            unlocking_coin?: ReturnType<typeof MultiStakingCoin.prototype.toObject>;
        }): UnlockEntry {
            const message = new UnlockEntry({});
            if (data.creation_height != null) {
                message.creation_height = data.creation_height;
            }
            if (data.unlocking_coin != null) {
                message.unlocking_coin = MultiStakingCoin.fromObject(data.unlocking_coin);
            }
            return message;
        }
        toObject() {
            const data: {
                creation_height?: number;
                unlocking_coin?: ReturnType<typeof MultiStakingCoin.prototype.toObject>;
            } = {};
            if (this.creation_height != null) {
                data.creation_height = this.creation_height;
            }
            if (this.unlocking_coin != null) {
                data.unlocking_coin = this.unlocking_coin.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.creation_height != 0)
                writer.writeInt64(1, this.creation_height);
            if (this.has_unlocking_coin)
                writer.writeMessage(2, this.unlocking_coin, () => this.unlocking_coin.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UnlockEntry {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UnlockEntry();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.creation_height = reader.readInt64();
                        break;
                    case 2:
                        reader.readMessage(message.unlocking_coin, () => message.unlocking_coin = MultiStakingCoin.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UnlockEntry {
            return UnlockEntry.deserialize(bytes);
        }
    }
    export class MultiStakingCoinInfo extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            denom?: string;
            bond_weight?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("denom" in data && data.denom != undefined) {
                    this.denom = data.denom;
                }
                if ("bond_weight" in data && data.bond_weight != undefined) {
                    this.bond_weight = data.bond_weight;
                }
            }
        }
        get denom() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set denom(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get bond_weight() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set bond_weight(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            denom?: string;
            bond_weight?: string;
        }): MultiStakingCoinInfo {
            const message = new MultiStakingCoinInfo({});
            if (data.denom != null) {
                message.denom = data.denom;
            }
            if (data.bond_weight != null) {
                message.bond_weight = data.bond_weight;
            }
            return message;
        }
        toObject() {
            const data: {
                denom?: string;
                bond_weight?: string;
            } = {};
            if (this.denom != null) {
                data.denom = this.denom;
            }
            if (this.bond_weight != null) {
                data.bond_weight = this.bond_weight;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.denom.length)
                writer.writeString(1, this.denom);
            if (this.bond_weight.length)
                writer.writeString(2, this.bond_weight);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MultiStakingCoinInfo {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MultiStakingCoinInfo();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.denom = reader.readString();
                        break;
                    case 2:
                        message.bond_weight = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MultiStakingCoinInfo {
            return MultiStakingCoinInfo.deserialize(bytes);
        }
    }
    export class ValidatorInfo extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            operator_address?: string;
            consensus_pubkey?: dependency_5.google.protobuf.Any;
            jailed?: boolean;
            status?: dependency_3.cosmos.staking.v1beta1.BondStatus;
            tokens?: string;
            delegator_shares?: string;
            description?: dependency_3.cosmos.staking.v1beta1.Description;
            unbonding_height?: number;
            unbonding_time?: dependency_4.google.protobuf.Timestamp;
            commission?: dependency_3.cosmos.staking.v1beta1.Commission;
            min_self_delegation?: string;
            bond_denom?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("operator_address" in data && data.operator_address != undefined) {
                    this.operator_address = data.operator_address;
                }
                if ("consensus_pubkey" in data && data.consensus_pubkey != undefined) {
                    this.consensus_pubkey = data.consensus_pubkey;
                }
                if ("jailed" in data && data.jailed != undefined) {
                    this.jailed = data.jailed;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("tokens" in data && data.tokens != undefined) {
                    this.tokens = data.tokens;
                }
                if ("delegator_shares" in data && data.delegator_shares != undefined) {
                    this.delegator_shares = data.delegator_shares;
                }
                if ("description" in data && data.description != undefined) {
                    this.description = data.description;
                }
                if ("unbonding_height" in data && data.unbonding_height != undefined) {
                    this.unbonding_height = data.unbonding_height;
                }
                if ("unbonding_time" in data && data.unbonding_time != undefined) {
                    this.unbonding_time = data.unbonding_time;
                }
                if ("commission" in data && data.commission != undefined) {
                    this.commission = data.commission;
                }
                if ("min_self_delegation" in data && data.min_self_delegation != undefined) {
                    this.min_self_delegation = data.min_self_delegation;
                }
                if ("bond_denom" in data && data.bond_denom != undefined) {
                    this.bond_denom = data.bond_denom;
                }
            }
        }
        get operator_address() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set operator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get consensus_pubkey() {
            return pb_1.Message.getWrapperField(this, dependency_5.google.protobuf.Any, 2) as dependency_5.google.protobuf.Any;
        }
        set consensus_pubkey(value: dependency_5.google.protobuf.Any) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_consensus_pubkey() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get jailed() {
            return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
        }
        set jailed(value: boolean) {
            pb_1.Message.setField(this, 3, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 4, dependency_3.cosmos.staking.v1beta1.BondStatus.BOND_STATUS_UNSPECIFIED) as dependency_3.cosmos.staking.v1beta1.BondStatus;
        }
        set status(value: dependency_3.cosmos.staking.v1beta1.BondStatus) {
            pb_1.Message.setField(this, 4, value);
        }
        get tokens() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set tokens(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get delegator_shares() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set delegator_shares(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get description() {
            return pb_1.Message.getWrapperField(this, dependency_3.cosmos.staking.v1beta1.Description, 7) as dependency_3.cosmos.staking.v1beta1.Description;
        }
        set description(value: dependency_3.cosmos.staking.v1beta1.Description) {
            pb_1.Message.setWrapperField(this, 7, value);
        }
        get has_description() {
            return pb_1.Message.getField(this, 7) != null;
        }
        get unbonding_height() {
            return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
        }
        set unbonding_height(value: number) {
            pb_1.Message.setField(this, 8, value);
        }
        get unbonding_time() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.protobuf.Timestamp, 9) as dependency_4.google.protobuf.Timestamp;
        }
        set unbonding_time(value: dependency_4.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 9, value);
        }
        get has_unbonding_time() {
            return pb_1.Message.getField(this, 9) != null;
        }
        get commission() {
            return pb_1.Message.getWrapperField(this, dependency_3.cosmos.staking.v1beta1.Commission, 10) as dependency_3.cosmos.staking.v1beta1.Commission;
        }
        set commission(value: dependency_3.cosmos.staking.v1beta1.Commission) {
            pb_1.Message.setWrapperField(this, 10, value);
        }
        get has_commission() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get min_self_delegation() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set min_self_delegation(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get bond_denom() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set bond_denom(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        static fromObject(data: {
            operator_address?: string;
            consensus_pubkey?: ReturnType<typeof dependency_5.google.protobuf.Any.prototype.toObject>;
            jailed?: boolean;
            status?: dependency_3.cosmos.staking.v1beta1.BondStatus;
            tokens?: string;
            delegator_shares?: string;
            description?: ReturnType<typeof dependency_3.cosmos.staking.v1beta1.Description.prototype.toObject>;
            unbonding_height?: number;
            unbonding_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
            commission?: ReturnType<typeof dependency_3.cosmos.staking.v1beta1.Commission.prototype.toObject>;
            min_self_delegation?: string;
            bond_denom?: string;
        }): ValidatorInfo {
            const message = new ValidatorInfo({});
            if (data.operator_address != null) {
                message.operator_address = data.operator_address;
            }
            if (data.consensus_pubkey != null) {
                message.consensus_pubkey = dependency_5.google.protobuf.Any.fromObject(data.consensus_pubkey);
            }
            if (data.jailed != null) {
                message.jailed = data.jailed;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.tokens != null) {
                message.tokens = data.tokens;
            }
            if (data.delegator_shares != null) {
                message.delegator_shares = data.delegator_shares;
            }
            if (data.description != null) {
                message.description = dependency_3.cosmos.staking.v1beta1.Description.fromObject(data.description);
            }
            if (data.unbonding_height != null) {
                message.unbonding_height = data.unbonding_height;
            }
            if (data.unbonding_time != null) {
                message.unbonding_time = dependency_4.google.protobuf.Timestamp.fromObject(data.unbonding_time);
            }
            if (data.commission != null) {
                message.commission = dependency_3.cosmos.staking.v1beta1.Commission.fromObject(data.commission);
            }
            if (data.min_self_delegation != null) {
                message.min_self_delegation = data.min_self_delegation;
            }
            if (data.bond_denom != null) {
                message.bond_denom = data.bond_denom;
            }
            return message;
        }
        toObject() {
            const data: {
                operator_address?: string;
                consensus_pubkey?: ReturnType<typeof dependency_5.google.protobuf.Any.prototype.toObject>;
                jailed?: boolean;
                status?: dependency_3.cosmos.staking.v1beta1.BondStatus;
                tokens?: string;
                delegator_shares?: string;
                description?: ReturnType<typeof dependency_3.cosmos.staking.v1beta1.Description.prototype.toObject>;
                unbonding_height?: number;
                unbonding_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
                commission?: ReturnType<typeof dependency_3.cosmos.staking.v1beta1.Commission.prototype.toObject>;
                min_self_delegation?: string;
                bond_denom?: string;
            } = {};
            if (this.operator_address != null) {
                data.operator_address = this.operator_address;
            }
            if (this.consensus_pubkey != null) {
                data.consensus_pubkey = this.consensus_pubkey.toObject();
            }
            if (this.jailed != null) {
                data.jailed = this.jailed;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.tokens != null) {
                data.tokens = this.tokens;
            }
            if (this.delegator_shares != null) {
                data.delegator_shares = this.delegator_shares;
            }
            if (this.description != null) {
                data.description = this.description.toObject();
            }
            if (this.unbonding_height != null) {
                data.unbonding_height = this.unbonding_height;
            }
            if (this.unbonding_time != null) {
                data.unbonding_time = this.unbonding_time.toObject();
            }
            if (this.commission != null) {
                data.commission = this.commission.toObject();
            }
            if (this.min_self_delegation != null) {
                data.min_self_delegation = this.min_self_delegation;
            }
            if (this.bond_denom != null) {
                data.bond_denom = this.bond_denom;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.operator_address.length)
                writer.writeString(1, this.operator_address);
            if (this.has_consensus_pubkey)
                writer.writeMessage(2, this.consensus_pubkey, () => this.consensus_pubkey.serialize(writer));
            if (this.jailed != false)
                writer.writeBool(3, this.jailed);
            if (this.status != dependency_3.cosmos.staking.v1beta1.BondStatus.BOND_STATUS_UNSPECIFIED)
                writer.writeEnum(4, this.status);
            if (this.tokens.length)
                writer.writeString(5, this.tokens);
            if (this.delegator_shares.length)
                writer.writeString(6, this.delegator_shares);
            if (this.has_description)
                writer.writeMessage(7, this.description, () => this.description.serialize(writer));
            if (this.unbonding_height != 0)
                writer.writeInt64(8, this.unbonding_height);
            if (this.has_unbonding_time)
                writer.writeMessage(9, this.unbonding_time, () => this.unbonding_time.serialize(writer));
            if (this.has_commission)
                writer.writeMessage(10, this.commission, () => this.commission.serialize(writer));
            if (this.min_self_delegation.length)
                writer.writeString(11, this.min_self_delegation);
            if (this.bond_denom.length)
                writer.writeString(12, this.bond_denom);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ValidatorInfo {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ValidatorInfo();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.operator_address = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.consensus_pubkey, () => message.consensus_pubkey = dependency_5.google.protobuf.Any.deserialize(reader));
                        break;
                    case 3:
                        message.jailed = reader.readBool();
                        break;
                    case 4:
                        message.status = reader.readEnum();
                        break;
                    case 5:
                        message.tokens = reader.readString();
                        break;
                    case 6:
                        message.delegator_shares = reader.readString();
                        break;
                    case 7:
                        reader.readMessage(message.description, () => message.description = dependency_3.cosmos.staking.v1beta1.Description.deserialize(reader));
                        break;
                    case 8:
                        message.unbonding_height = reader.readInt64();
                        break;
                    case 9:
                        reader.readMessage(message.unbonding_time, () => message.unbonding_time = dependency_4.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 10:
                        reader.readMessage(message.commission, () => message.commission = dependency_3.cosmos.staking.v1beta1.Commission.deserialize(reader));
                        break;
                    case 11:
                        message.min_self_delegation = reader.readString();
                        break;
                    case 12:
                        message.bond_denom = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ValidatorInfo {
            return ValidatorInfo.deserialize(bytes);
        }
    }
}
