/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.1
 * source: realionetwork/multistaking/v1/tx.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../gogoproto/gogo";
import * as dependency_2 from "./../../../cosmos/msg/v1/msg";
import * as dependency_3 from "./../../../cosmos_proto/cosmos";
import * as dependency_4 from "./../../../cosmos/staking/v1beta1/staking";
import * as dependency_5 from "./../../../google/protobuf/any";
import * as dependency_6 from "./../../../google/protobuf/timestamp";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace multistaking.v1 {
    export class MsgCreateEVMValidator extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            description?: dependency_4.cosmos.staking.v1beta1.Description;
            commission?: dependency_4.cosmos.staking.v1beta1.CommissionRates;
            min_self_delegation?: string;
            /** @deprecated*/
            delegator_address?: string;
            validator_address?: string;
            pubkey?: dependency_5.google.protobuf.Any;
            contract_address?: string;
            value?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("description" in data && data.description != undefined) {
                    this.description = data.description;
                }
                if ("commission" in data && data.commission != undefined) {
                    this.commission = data.commission;
                }
                if ("min_self_delegation" in data && data.min_self_delegation != undefined) {
                    this.min_self_delegation = data.min_self_delegation;
                }
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
                if ("validator_address" in data && data.validator_address != undefined) {
                    this.validator_address = data.validator_address;
                }
                if ("pubkey" in data && data.pubkey != undefined) {
                    this.pubkey = data.pubkey;
                }
                if ("contract_address" in data && data.contract_address != undefined) {
                    this.contract_address = data.contract_address;
                }
                if ("value" in data && data.value != undefined) {
                    this.value = data.value;
                }
            }
        }
        get description() {
            return pb_1.Message.getWrapperField(this, dependency_4.cosmos.staking.v1beta1.Description, 1) as dependency_4.cosmos.staking.v1beta1.Description;
        }
        set description(value: dependency_4.cosmos.staking.v1beta1.Description) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_description() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get commission() {
            return pb_1.Message.getWrapperField(this, dependency_4.cosmos.staking.v1beta1.CommissionRates, 2) as dependency_4.cosmos.staking.v1beta1.CommissionRates;
        }
        set commission(value: dependency_4.cosmos.staking.v1beta1.CommissionRates) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_commission() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get min_self_delegation() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set min_self_delegation(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        /** @deprecated*/
        get delegator_address() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        /** @deprecated*/
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get validator_address() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set validator_address(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get pubkey() {
            return pb_1.Message.getWrapperField(this, dependency_5.google.protobuf.Any, 6) as dependency_5.google.protobuf.Any;
        }
        set pubkey(value: dependency_5.google.protobuf.Any) {
            pb_1.Message.setWrapperField(this, 6, value);
        }
        get has_pubkey() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get contract_address() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set contract_address(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        get value() {
            return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
        }
        set value(value: string) {
            pb_1.Message.setField(this, 8, value);
        }
        static fromObject(data: {
            description?: ReturnType<typeof dependency_4.cosmos.staking.v1beta1.Description.prototype.toObject>;
            commission?: ReturnType<typeof dependency_4.cosmos.staking.v1beta1.CommissionRates.prototype.toObject>;
            min_self_delegation?: string;
            delegator_address?: string;
            validator_address?: string;
            pubkey?: ReturnType<typeof dependency_5.google.protobuf.Any.prototype.toObject>;
            contract_address?: string;
            value?: string;
        }): MsgCreateEVMValidator {
            const message = new MsgCreateEVMValidator({});
            if (data.description != null) {
                message.description = dependency_4.cosmos.staking.v1beta1.Description.fromObject(data.description);
            }
            if (data.commission != null) {
                message.commission = dependency_4.cosmos.staking.v1beta1.CommissionRates.fromObject(data.commission);
            }
            if (data.min_self_delegation != null) {
                message.min_self_delegation = data.min_self_delegation;
            }
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            if (data.validator_address != null) {
                message.validator_address = data.validator_address;
            }
            if (data.pubkey != null) {
                message.pubkey = dependency_5.google.protobuf.Any.fromObject(data.pubkey);
            }
            if (data.contract_address != null) {
                message.contract_address = data.contract_address;
            }
            if (data.value != null) {
                message.value = data.value;
            }
            return message;
        }
        toObject() {
            const data: {
                description?: ReturnType<typeof dependency_4.cosmos.staking.v1beta1.Description.prototype.toObject>;
                commission?: ReturnType<typeof dependency_4.cosmos.staking.v1beta1.CommissionRates.prototype.toObject>;
                min_self_delegation?: string;
                delegator_address?: string;
                validator_address?: string;
                pubkey?: ReturnType<typeof dependency_5.google.protobuf.Any.prototype.toObject>;
                contract_address?: string;
                value?: string;
            } = {};
            if (this.description != null) {
                data.description = this.description.toObject();
            }
            if (this.commission != null) {
                data.commission = this.commission.toObject();
            }
            if (this.min_self_delegation != null) {
                data.min_self_delegation = this.min_self_delegation;
            }
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            if (this.validator_address != null) {
                data.validator_address = this.validator_address;
            }
            if (this.pubkey != null) {
                data.pubkey = this.pubkey.toObject();
            }
            if (this.contract_address != null) {
                data.contract_address = this.contract_address;
            }
            if (this.value != null) {
                data.value = this.value;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_description)
                writer.writeMessage(1, this.description, () => this.description.serialize(writer));
            if (this.has_commission)
                writer.writeMessage(2, this.commission, () => this.commission.serialize(writer));
            if (this.min_self_delegation.length)
                writer.writeString(3, this.min_self_delegation);
            if (this.delegator_address.length)
                writer.writeString(4, this.delegator_address);
            if (this.validator_address.length)
                writer.writeString(5, this.validator_address);
            if (this.has_pubkey)
                writer.writeMessage(6, this.pubkey, () => this.pubkey.serialize(writer));
            if (this.contract_address.length)
                writer.writeString(7, this.contract_address);
            if (this.value.length)
                writer.writeString(8, this.value);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgCreateEVMValidator {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgCreateEVMValidator();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.description, () => message.description = dependency_4.cosmos.staking.v1beta1.Description.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.commission, () => message.commission = dependency_4.cosmos.staking.v1beta1.CommissionRates.deserialize(reader));
                        break;
                    case 3:
                        message.min_self_delegation = reader.readString();
                        break;
                    case 4:
                        message.delegator_address = reader.readString();
                        break;
                    case 5:
                        message.validator_address = reader.readString();
                        break;
                    case 6:
                        reader.readMessage(message.pubkey, () => message.pubkey = dependency_5.google.protobuf.Any.deserialize(reader));
                        break;
                    case 7:
                        message.contract_address = reader.readString();
                        break;
                    case 8:
                        message.value = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgCreateEVMValidator {
            return MsgCreateEVMValidator.deserialize(bytes);
        }
    }
    export class MsgCreateEVMValidatorResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): MsgCreateEVMValidatorResponse {
            const message = new MsgCreateEVMValidatorResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgCreateEVMValidatorResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgCreateEVMValidatorResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgCreateEVMValidatorResponse {
            return MsgCreateEVMValidatorResponse.deserialize(bytes);
        }
    }
    export class MsgDelegateEVM extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            delegator_address?: string;
            validator_address?: string;
            contract_address?: string;
            amount?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
                if ("validator_address" in data && data.validator_address != undefined) {
                    this.validator_address = data.validator_address;
                }
                if ("contract_address" in data && data.contract_address != undefined) {
                    this.contract_address = data.contract_address;
                }
                if ("amount" in data && data.amount != undefined) {
                    this.amount = data.amount;
                }
            }
        }
        get delegator_address() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get validator_address() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set validator_address(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get contract_address() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set contract_address(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get amount() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set amount(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            delegator_address?: string;
            validator_address?: string;
            contract_address?: string;
            amount?: string;
        }): MsgDelegateEVM {
            const message = new MsgDelegateEVM({});
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            if (data.validator_address != null) {
                message.validator_address = data.validator_address;
            }
            if (data.contract_address != null) {
                message.contract_address = data.contract_address;
            }
            if (data.amount != null) {
                message.amount = data.amount;
            }
            return message;
        }
        toObject() {
            const data: {
                delegator_address?: string;
                validator_address?: string;
                contract_address?: string;
                amount?: string;
            } = {};
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            if (this.validator_address != null) {
                data.validator_address = this.validator_address;
            }
            if (this.contract_address != null) {
                data.contract_address = this.contract_address;
            }
            if (this.amount != null) {
                data.amount = this.amount;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.delegator_address.length)
                writer.writeString(1, this.delegator_address);
            if (this.validator_address.length)
                writer.writeString(2, this.validator_address);
            if (this.contract_address.length)
                writer.writeString(3, this.contract_address);
            if (this.amount.length)
                writer.writeString(4, this.amount);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgDelegateEVM {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgDelegateEVM();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delegator_address = reader.readString();
                        break;
                    case 2:
                        message.validator_address = reader.readString();
                        break;
                    case 3:
                        message.contract_address = reader.readString();
                        break;
                    case 4:
                        message.amount = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgDelegateEVM {
            return MsgDelegateEVM.deserialize(bytes);
        }
    }
    export class MsgDelegateEVMResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): MsgDelegateEVMResponse {
            const message = new MsgDelegateEVMResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgDelegateEVMResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgDelegateEVMResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgDelegateEVMResponse {
            return MsgDelegateEVMResponse.deserialize(bytes);
        }
    }
    export class MsgBeginRedelegateEVM extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            delegator_address?: string;
            validator_src_address?: string;
            validator_dst_address?: string;
            contract_address?: string;
            amount?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
                if ("validator_src_address" in data && data.validator_src_address != undefined) {
                    this.validator_src_address = data.validator_src_address;
                }
                if ("validator_dst_address" in data && data.validator_dst_address != undefined) {
                    this.validator_dst_address = data.validator_dst_address;
                }
                if ("contract_address" in data && data.contract_address != undefined) {
                    this.contract_address = data.contract_address;
                }
                if ("amount" in data && data.amount != undefined) {
                    this.amount = data.amount;
                }
            }
        }
        get delegator_address() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get validator_src_address() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set validator_src_address(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get validator_dst_address() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set validator_dst_address(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get contract_address() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set contract_address(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get amount() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set amount(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            delegator_address?: string;
            validator_src_address?: string;
            validator_dst_address?: string;
            contract_address?: string;
            amount?: string;
        }): MsgBeginRedelegateEVM {
            const message = new MsgBeginRedelegateEVM({});
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            if (data.validator_src_address != null) {
                message.validator_src_address = data.validator_src_address;
            }
            if (data.validator_dst_address != null) {
                message.validator_dst_address = data.validator_dst_address;
            }
            if (data.contract_address != null) {
                message.contract_address = data.contract_address;
            }
            if (data.amount != null) {
                message.amount = data.amount;
            }
            return message;
        }
        toObject() {
            const data: {
                delegator_address?: string;
                validator_src_address?: string;
                validator_dst_address?: string;
                contract_address?: string;
                amount?: string;
            } = {};
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            if (this.validator_src_address != null) {
                data.validator_src_address = this.validator_src_address;
            }
            if (this.validator_dst_address != null) {
                data.validator_dst_address = this.validator_dst_address;
            }
            if (this.contract_address != null) {
                data.contract_address = this.contract_address;
            }
            if (this.amount != null) {
                data.amount = this.amount;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.delegator_address.length)
                writer.writeString(1, this.delegator_address);
            if (this.validator_src_address.length)
                writer.writeString(2, this.validator_src_address);
            if (this.validator_dst_address.length)
                writer.writeString(3, this.validator_dst_address);
            if (this.contract_address.length)
                writer.writeString(4, this.contract_address);
            if (this.amount.length)
                writer.writeString(5, this.amount);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgBeginRedelegateEVM {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgBeginRedelegateEVM();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delegator_address = reader.readString();
                        break;
                    case 2:
                        message.validator_src_address = reader.readString();
                        break;
                    case 3:
                        message.validator_dst_address = reader.readString();
                        break;
                    case 4:
                        message.contract_address = reader.readString();
                        break;
                    case 5:
                        message.amount = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgBeginRedelegateEVM {
            return MsgBeginRedelegateEVM.deserialize(bytes);
        }
    }
    export class MsgBeginRedelegateEVMResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            completion_time?: dependency_6.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("completion_time" in data && data.completion_time != undefined) {
                    this.completion_time = data.completion_time;
                }
            }
        }
        get completion_time() {
            return pb_1.Message.getWrapperField(this, dependency_6.google.protobuf.Timestamp, 1) as dependency_6.google.protobuf.Timestamp;
        }
        set completion_time(value: dependency_6.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_completion_time() {
            return pb_1.Message.getField(this, 1) != null;
        }
        static fromObject(data: {
            completion_time?: ReturnType<typeof dependency_6.google.protobuf.Timestamp.prototype.toObject>;
        }): MsgBeginRedelegateEVMResponse {
            const message = new MsgBeginRedelegateEVMResponse({});
            if (data.completion_time != null) {
                message.completion_time = dependency_6.google.protobuf.Timestamp.fromObject(data.completion_time);
            }
            return message;
        }
        toObject() {
            const data: {
                completion_time?: ReturnType<typeof dependency_6.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.completion_time != null) {
                data.completion_time = this.completion_time.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_completion_time)
                writer.writeMessage(1, this.completion_time, () => this.completion_time.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgBeginRedelegateEVMResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgBeginRedelegateEVMResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.completion_time, () => message.completion_time = dependency_6.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgBeginRedelegateEVMResponse {
            return MsgBeginRedelegateEVMResponse.deserialize(bytes);
        }
    }
    export class MsgUndelegateEVM extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            delegator_address?: string;
            validator_address?: string;
            contract_address?: string;
            amount?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
                if ("validator_address" in data && data.validator_address != undefined) {
                    this.validator_address = data.validator_address;
                }
                if ("contract_address" in data && data.contract_address != undefined) {
                    this.contract_address = data.contract_address;
                }
                if ("amount" in data && data.amount != undefined) {
                    this.amount = data.amount;
                }
            }
        }
        get delegator_address() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get validator_address() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set validator_address(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get contract_address() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set contract_address(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get amount() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set amount(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            delegator_address?: string;
            validator_address?: string;
            contract_address?: string;
            amount?: string;
        }): MsgUndelegateEVM {
            const message = new MsgUndelegateEVM({});
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            if (data.validator_address != null) {
                message.validator_address = data.validator_address;
            }
            if (data.contract_address != null) {
                message.contract_address = data.contract_address;
            }
            if (data.amount != null) {
                message.amount = data.amount;
            }
            return message;
        }
        toObject() {
            const data: {
                delegator_address?: string;
                validator_address?: string;
                contract_address?: string;
                amount?: string;
            } = {};
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            if (this.validator_address != null) {
                data.validator_address = this.validator_address;
            }
            if (this.contract_address != null) {
                data.contract_address = this.contract_address;
            }
            if (this.amount != null) {
                data.amount = this.amount;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.delegator_address.length)
                writer.writeString(1, this.delegator_address);
            if (this.validator_address.length)
                writer.writeString(2, this.validator_address);
            if (this.contract_address.length)
                writer.writeString(3, this.contract_address);
            if (this.amount.length)
                writer.writeString(4, this.amount);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgUndelegateEVM {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgUndelegateEVM();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delegator_address = reader.readString();
                        break;
                    case 2:
                        message.validator_address = reader.readString();
                        break;
                    case 3:
                        message.contract_address = reader.readString();
                        break;
                    case 4:
                        message.amount = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgUndelegateEVM {
            return MsgUndelegateEVM.deserialize(bytes);
        }
    }
    export class MsgUndelegateEVMResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            completion_time?: dependency_6.google.protobuf.Timestamp;
            contract_address?: string;
            amount?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("completion_time" in data && data.completion_time != undefined) {
                    this.completion_time = data.completion_time;
                }
                if ("contract_address" in data && data.contract_address != undefined) {
                    this.contract_address = data.contract_address;
                }
                if ("amount" in data && data.amount != undefined) {
                    this.amount = data.amount;
                }
            }
        }
        get completion_time() {
            return pb_1.Message.getWrapperField(this, dependency_6.google.protobuf.Timestamp, 1) as dependency_6.google.protobuf.Timestamp;
        }
        set completion_time(value: dependency_6.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_completion_time() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get contract_address() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set contract_address(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get amount() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set amount(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            completion_time?: ReturnType<typeof dependency_6.google.protobuf.Timestamp.prototype.toObject>;
            contract_address?: string;
            amount?: string;
        }): MsgUndelegateEVMResponse {
            const message = new MsgUndelegateEVMResponse({});
            if (data.completion_time != null) {
                message.completion_time = dependency_6.google.protobuf.Timestamp.fromObject(data.completion_time);
            }
            if (data.contract_address != null) {
                message.contract_address = data.contract_address;
            }
            if (data.amount != null) {
                message.amount = data.amount;
            }
            return message;
        }
        toObject() {
            const data: {
                completion_time?: ReturnType<typeof dependency_6.google.protobuf.Timestamp.prototype.toObject>;
                contract_address?: string;
                amount?: string;
            } = {};
            if (this.completion_time != null) {
                data.completion_time = this.completion_time.toObject();
            }
            if (this.contract_address != null) {
                data.contract_address = this.contract_address;
            }
            if (this.amount != null) {
                data.amount = this.amount;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_completion_time)
                writer.writeMessage(1, this.completion_time, () => this.completion_time.serialize(writer));
            if (this.contract_address.length)
                writer.writeString(4, this.contract_address);
            if (this.amount.length)
                writer.writeString(5, this.amount);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgUndelegateEVMResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgUndelegateEVMResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.completion_time, () => message.completion_time = dependency_6.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 4:
                        message.contract_address = reader.readString();
                        break;
                    case 5:
                        message.amount = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgUndelegateEVMResponse {
            return MsgUndelegateEVMResponse.deserialize(bytes);
        }
    }
    export class MsgCancelUnbondingEVMDelegation extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            delegator_address?: string;
            validator_address?: string;
            contract_address?: string;
            amount?: string;
            creation_height?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("delegator_address" in data && data.delegator_address != undefined) {
                    this.delegator_address = data.delegator_address;
                }
                if ("validator_address" in data && data.validator_address != undefined) {
                    this.validator_address = data.validator_address;
                }
                if ("contract_address" in data && data.contract_address != undefined) {
                    this.contract_address = data.contract_address;
                }
                if ("amount" in data && data.amount != undefined) {
                    this.amount = data.amount;
                }
                if ("creation_height" in data && data.creation_height != undefined) {
                    this.creation_height = data.creation_height;
                }
            }
        }
        get delegator_address() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set delegator_address(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get validator_address() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set validator_address(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get contract_address() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set contract_address(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get amount() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set amount(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get creation_height() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set creation_height(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            delegator_address?: string;
            validator_address?: string;
            contract_address?: string;
            amount?: string;
            creation_height?: number;
        }): MsgCancelUnbondingEVMDelegation {
            const message = new MsgCancelUnbondingEVMDelegation({});
            if (data.delegator_address != null) {
                message.delegator_address = data.delegator_address;
            }
            if (data.validator_address != null) {
                message.validator_address = data.validator_address;
            }
            if (data.contract_address != null) {
                message.contract_address = data.contract_address;
            }
            if (data.amount != null) {
                message.amount = data.amount;
            }
            if (data.creation_height != null) {
                message.creation_height = data.creation_height;
            }
            return message;
        }
        toObject() {
            const data: {
                delegator_address?: string;
                validator_address?: string;
                contract_address?: string;
                amount?: string;
                creation_height?: number;
            } = {};
            if (this.delegator_address != null) {
                data.delegator_address = this.delegator_address;
            }
            if (this.validator_address != null) {
                data.validator_address = this.validator_address;
            }
            if (this.contract_address != null) {
                data.contract_address = this.contract_address;
            }
            if (this.amount != null) {
                data.amount = this.amount;
            }
            if (this.creation_height != null) {
                data.creation_height = this.creation_height;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.delegator_address.length)
                writer.writeString(1, this.delegator_address);
            if (this.validator_address.length)
                writer.writeString(2, this.validator_address);
            if (this.contract_address.length)
                writer.writeString(3, this.contract_address);
            if (this.amount.length)
                writer.writeString(4, this.amount);
            if (this.creation_height != 0)
                writer.writeInt64(5, this.creation_height);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgCancelUnbondingEVMDelegation {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgCancelUnbondingEVMDelegation();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.delegator_address = reader.readString();
                        break;
                    case 2:
                        message.validator_address = reader.readString();
                        break;
                    case 3:
                        message.contract_address = reader.readString();
                        break;
                    case 4:
                        message.amount = reader.readString();
                        break;
                    case 5:
                        message.creation_height = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgCancelUnbondingEVMDelegation {
            return MsgCancelUnbondingEVMDelegation.deserialize(bytes);
        }
    }
    export class MsgCancelUnbondingEVMDelegationResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): MsgCancelUnbondingEVMDelegationResponse {
            const message = new MsgCancelUnbondingEVMDelegationResponse({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MsgCancelUnbondingEVMDelegationResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MsgCancelUnbondingEVMDelegationResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MsgCancelUnbondingEVMDelegationResponse {
            return MsgCancelUnbondingEVMDelegationResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedMsgService {
        static definition = {
            CreateEVMValidator: {
                path: "/multistaking.v1.Msg/CreateEVMValidator",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: MsgCreateEVMValidator) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => MsgCreateEVMValidator.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: MsgCreateEVMValidatorResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => MsgCreateEVMValidatorResponse.deserialize(new Uint8Array(bytes))
            },
            DelegateEVM: {
                path: "/multistaking.v1.Msg/DelegateEVM",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: MsgDelegateEVM) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => MsgDelegateEVM.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: MsgDelegateEVMResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => MsgDelegateEVMResponse.deserialize(new Uint8Array(bytes))
            },
            BeginRedelegateEVM: {
                path: "/multistaking.v1.Msg/BeginRedelegateEVM",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: MsgBeginRedelegateEVM) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => MsgBeginRedelegateEVM.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: MsgBeginRedelegateEVMResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => MsgBeginRedelegateEVMResponse.deserialize(new Uint8Array(bytes))
            },
            UndelegateEVM: {
                path: "/multistaking.v1.Msg/UndelegateEVM",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: MsgUndelegateEVM) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => MsgUndelegateEVM.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: MsgUndelegateEVMResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => MsgUndelegateEVMResponse.deserialize(new Uint8Array(bytes))
            },
            CancelUnbondingEVMDelegation: {
                path: "/multistaking.v1.Msg/CancelUnbondingEVMDelegation",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: MsgCancelUnbondingEVMDelegation) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => MsgCancelUnbondingEVMDelegation.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: MsgCancelUnbondingEVMDelegationResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => MsgCancelUnbondingEVMDelegationResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract CreateEVMValidator(call: grpc_1.ServerUnaryCall<MsgCreateEVMValidator, MsgCreateEVMValidatorResponse>, callback: grpc_1.sendUnaryData<MsgCreateEVMValidatorResponse>): void;
        abstract DelegateEVM(call: grpc_1.ServerUnaryCall<MsgDelegateEVM, MsgDelegateEVMResponse>, callback: grpc_1.sendUnaryData<MsgDelegateEVMResponse>): void;
        abstract BeginRedelegateEVM(call: grpc_1.ServerUnaryCall<MsgBeginRedelegateEVM, MsgBeginRedelegateEVMResponse>, callback: grpc_1.sendUnaryData<MsgBeginRedelegateEVMResponse>): void;
        abstract UndelegateEVM(call: grpc_1.ServerUnaryCall<MsgUndelegateEVM, MsgUndelegateEVMResponse>, callback: grpc_1.sendUnaryData<MsgUndelegateEVMResponse>): void;
        abstract CancelUnbondingEVMDelegation(call: grpc_1.ServerUnaryCall<MsgCancelUnbondingEVMDelegation, MsgCancelUnbondingEVMDelegationResponse>, callback: grpc_1.sendUnaryData<MsgCancelUnbondingEVMDelegationResponse>): void;
    }
    export class MsgClient extends grpc_1.makeGenericClientConstructor(UnimplementedMsgService.definition, "Msg", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        CreateEVMValidator: GrpcUnaryServiceInterface<MsgCreateEVMValidator, MsgCreateEVMValidatorResponse> = (message: MsgCreateEVMValidator, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<MsgCreateEVMValidatorResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<MsgCreateEVMValidatorResponse>, callback?: grpc_1.requestCallback<MsgCreateEVMValidatorResponse>): grpc_1.ClientUnaryCall => {
            return super.CreateEVMValidator(message, metadata, options, callback);
        };
        DelegateEVM: GrpcUnaryServiceInterface<MsgDelegateEVM, MsgDelegateEVMResponse> = (message: MsgDelegateEVM, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<MsgDelegateEVMResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<MsgDelegateEVMResponse>, callback?: grpc_1.requestCallback<MsgDelegateEVMResponse>): grpc_1.ClientUnaryCall => {
            return super.DelegateEVM(message, metadata, options, callback);
        };
        BeginRedelegateEVM: GrpcUnaryServiceInterface<MsgBeginRedelegateEVM, MsgBeginRedelegateEVMResponse> = (message: MsgBeginRedelegateEVM, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<MsgBeginRedelegateEVMResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<MsgBeginRedelegateEVMResponse>, callback?: grpc_1.requestCallback<MsgBeginRedelegateEVMResponse>): grpc_1.ClientUnaryCall => {
            return super.BeginRedelegateEVM(message, metadata, options, callback);
        };
        UndelegateEVM: GrpcUnaryServiceInterface<MsgUndelegateEVM, MsgUndelegateEVMResponse> = (message: MsgUndelegateEVM, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<MsgUndelegateEVMResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<MsgUndelegateEVMResponse>, callback?: grpc_1.requestCallback<MsgUndelegateEVMResponse>): grpc_1.ClientUnaryCall => {
            return super.UndelegateEVM(message, metadata, options, callback);
        };
        CancelUnbondingEVMDelegation: GrpcUnaryServiceInterface<MsgCancelUnbondingEVMDelegation, MsgCancelUnbondingEVMDelegationResponse> = (message: MsgCancelUnbondingEVMDelegation, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<MsgCancelUnbondingEVMDelegationResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<MsgCancelUnbondingEVMDelegationResponse>, callback?: grpc_1.requestCallback<MsgCancelUnbondingEVMDelegationResponse>): grpc_1.ClientUnaryCall => {
            return super.CancelUnbondingEVMDelegation(message, metadata, options, callback);
        };
    }
}
